const activities = [
  "Hiking & Trekking",
  "Scuba Diving & Snorkeling",
  "Cultural Tours",
  "Wildlife Safari",
  "Beach & Relaxation",
  "Skiing & Snowboarding",
  "Food & Wine Tasting",
  "Historical Sightseeing",
  "Adventure Sports",
  "Photography",
  "Surfing",
  "Kayaking & Canoeing",
  "Rock Climbing",
  "Zip-lining",
  "Hot Air Ballooning",
  "Cycling Tours",
  "Fishing",
  "Sailing & Boating",
  "Camping",
  "Yoga & Wellness Retreats",
  "Birdwatching",
  "Volcano Tours",
  "Cave Exploration",
  "Paragliding",
  "Nightlife & Entertainment",
];

const randomActivity = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2] as const;
};

const destinationData = [
  {
    name: "Machu Picchu",
    country: "Peru",
    region: "South America",
    costLevel: "Moderate",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 150,
    annualVisitors: 1500000,
  },
  {
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    costLevel: "Premium",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 250,
    annualVisitors: 2000000,
  },
  {
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    costLevel: "Moderate",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 180,
    annualVisitors: 5300000,
  },
  {
    name: "Serengeti National Park",
    country: "Tanzania",
    region: "Africa",
    costLevel: "Premium",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 300,
    annualVisitors: 350000,
  },
  {
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    costLevel: "Premium",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 200,
    annualVisitors: 3000000,
  },
  {
    name: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    costLevel: "Premium",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 280,
    annualVisitors: 2300000,
  },
  {
    name: "Cusco",
    country: "Peru",
    region: "South America",
    costLevel: "Budget",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 60,
    annualVisitors: 2700000,
  },
  {
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    costLevel: "Budget",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 70,
    annualVisitors: 6200000,
  },
  {
    name: "Banff National Park",
    country: "Canada",
    region: "North America",
    costLevel: "Moderate",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 180,
    annualVisitors: 4000000,
  },
  {
    name: "Patagonia",
    country: "Argentina",
    region: "South America",
    costLevel: "Premium",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 220,
    annualVisitors: 400000,
  },
  {
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    costLevel: "Budget",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 55,
    annualVisitors: 3000000,
  },
  {
    name: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    costLevel: "Moderate",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 160,
    annualVisitors: 1400000,
  },
  {
    name: "Cancun",
    country: "Mexico",
    region: "North America",
    costLevel: "Moderate",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 140,
    annualVisitors: 8000000,
  },
  {
    name: "Phuket",
    country: "Thailand",
    region: "Asia",
    costLevel: "Budget",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 80,
    annualVisitors: 9500000,
  },
  {
    name: "Swiss Alps",
    country: "Switzerland",
    region: "Europe",
    costLevel: "Luxury",
    activities: activities.slice(...randomActivity()),
    averageDailyBudget: 400,
    annualVisitors: 1200000,
  },
];

export { destinationData };
